### ISSUE TITLE
gpg-agent not killed after unshare support was added

### ISSUE THREAD

**Issue by klausenbusk** [archlinux/arch-install-scripts#21]
Years ago a change was implemented forcing the `chroot` to run in its own PID namespace (https://github.com/archlinux/arch-install-scripts/commit/2be79c6259cfbf9ebcd258a68fea3ec79f532e32), this was done to ensure the `gpg-agent` (often started by `pacman-key` or `pacman`) was killed before exiting the `chroot`. Without this change you could risk getting a `umount: /mnt/dev: target is busy` error when existing the `chroot` due to the agent keeping `/dev/{u,}random` open (AFAIU).

With the newest release of `arch-install-scripts`, there are reports indicating that `gpg-agent` isn't killed anymore before exiting the `chroot`. As reported on our [bug tracker](https://bugs.archlinux.org/task/75378) and [reddit](https://www.reddit.com/r/archlinux/comments/wa0l7j/pacstrap_fails_because_it_cannot_umount_mntdev/).

Looking into the biggest change in the latest release (https://github.com/archlinux/arch-install-scripts/pull/14). AFAIU the `chroot` setup and teardown is now done inside the PID namespace, where before it was done outside the PID namespace. Which means `gpg-agent` is first killed after the `chroot` teardown.

This following patch seems to fix `arch-chroot` (`pacstrap` is still broken):
```diff
diff --git a/arch-chroot.in b/arch-chroot.in
index bcb38df..fdae328 100644
--- a/arch-chroot.in
+++ b/arch-chroot.in
@@ -116,7 +116,7 @@ arch-chroot() {
   chroot_args=()
   [[ $userspec ]] && chroot_args+=(--userspec "$userspec")
 
-  SHELL=/bin/bash chroot "${chroot_args[@]}" -- "$chrootdir" "${args[@]}"
+  SHELL=/bin/bash unshare --fork --pid chroot "${chroot_args[@]}" -- "$chrootdir" "${args[@]}"
 }
 
 args=("$@")
```

I'm unsure if it is the best way to fix the issue tho.

@Forty-Bot do you want to chime in? :)

**Comment by nkukard** [comment]
Here is a patch I tested with the various environments I run. I use arch-chroot for other things and I need them to be explicitly killed and only have access to their own namespace. But this fixes the issue thats being reported aswell. Perhaps it can be of some use.

```
diff --git a/common b/common
index bc2a334..669c0c5 100644
--- a/common
+++ b/common
@@ -152,8 +150,8 @@ unshare_teardown() {
   unset CHROOT_ACTIVE_FILES
 }

-root_unshare="unshare --fork --pid"
-user_unshare="$root_unshare --mount --map-auto --map-root-user --setuid 0 --setgid 0"
+root_unshare="unshare --fork --kill-child=SIGTERM --mount-proc"
+user_unshare="$root_unshare --map-auto --map-root-user --setuid 0 --setgid 0"

 # This outputs code for declaring all variables to stdout. For example, if
 # FOO=BAR, then running
```
