### ISSUE TITLE
error: GPGME error: No data

### ISSUE THREAD

**Issue by happycode202** [archlinux/arch-install-scripts#41]

**Comment by YHNdnzj** [comment]
Please contact your ISP. There's nothing we can do about the HTTP MITM attack.

Or, as you suggested, please manually check if you are using HTTPS mirrors.

**Comment by happycode202** [comment]
sorry ,i make a misstake,i wanted to do this in another project.
I'll delete it later

**Comment by jelly** [comment]
No description, closing.
