### ISSUE TITLE
Pacstrap /mnt base

### ISSUE THREAD

**Issue by lunics** [archlinux/arch-install-scripts#43]
My BTRFS filesystem has this mount points
/mnt/
/mnt/home
/mnt/opt
/mnt/usr
/mnt/var

Every time I run pacstrap /mnt base, it doesn't copy/link the /mnt/bin directory and skip many other operations, then return a "base is already installed"

**Comment by Foxboron** [comment]
Please give clear instructions on how to reproduce the issue. Including the output of mount and how you ran `pacstrap`.

**Comment by lunics** [comment]
Before running pacstrap my /mnt/chroot is empty, just the directories of btrfs subvolumes mounted are present and empty as well

**Comment by Foxboron** [comment]
You haven't posted a reproduction of the issue. You have just listed the current mount points and what is happening if you reinstall base.  

The issue isn't with `base`, it's with the `filesystem` package.

**Comment by lunics** [comment]
Can you explain to me what is the filesystem package ?
How can I send you that ?

**Comment by YHNdnzj** [comment]
`base` is a metapackage, which means it doesn't really do anything or install any files, but instead pulls in a set of packages that are really responsible. The package that holds symlinks like `/lib` and `/bin` is `filesystem`, so you should try (re-)installing that and see how things will go.

**Comment by lunics** [comment]
Ok `filesystem` is simply the name of the package sorry.

<details>
<summary>pacman -Sy filesystem</summary>
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community                                              7.3 MiB  5.06 MiB/s 00:01 [-----------------------------------------------] 100%
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) filesystem-2023.01.31-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.02 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 filesystem-2023.01.31-1-x86_64                        14.7 KiB   864 KiB/s 00:00 [-----------------------------------------------] 100%
(1/1) checking keys in keyring                                                    [-----------------------------------------------] 100%
(1/1) checking package integrity                                                  [-----------------------------------------------] 100%
(1/1) loading package files                                                       [-----------------------------------------------] 100%
(1/1) checking for file conflicts                                                 [-----------------------------------------------] 100%
(1/1) checking available disk space                                               [-----------------------------------------------] 100%
:: Processing package changes...
(1/1) upgrading filesystem                                                        [-----------------------------------------------] 100%
warning: /etc/shells installed as /etc/shells.pacnew
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
(2/4) Applying kernel sysctl settings...
(3/4) Creating temporary files...
(4/4) Arming ConditionNeedsUpdate...
</details>

<details>
<summary>pacstrap /mnt/chroot filesystem</summary>
==> Creating install root at /mnt/chroot
==> Installing packages to /mnt/chroot
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: filesystem-2023.01.31-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) filesystem-2023.01.31-1

Total Installed Size:  0.02 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                    [-----------------------------------------------] 100%
(1/1) checking package integrity                                                  [-----------------------------------------------] 100%
(1/1) loading package files                                                       [-----------------------------------------------] 100%
(1/1) checking for file conflicts                                                 [-----------------------------------------------] 100%
(1/1) checking available disk space                                               [-----------------------------------------------] 100%
warning: could not get file information for bin
warning: could not get file information for etc/arch-release
warning: could not get file information for etc/crypttab
warning: could not get file information for etc/fstab
warning: could not get file information for etc/group
warning: could not get file information for etc/gshadow
warning: could not get file information for etc/host.conf
warning: could not get file information for etc/hosts
...
</details>

**Comment by Foxboron** [comment]
@captkuykuy Kindly don't engage in such behaviour on our bugtracker.

**Comment by lunics** [comment]
Hi, I don't know what exactly causes the issue but I found where it comes from. 
My ansible pacman role run something like this:
```
pacman -Sy archlinux-keyring
pacman-key --init
pacman-key --populate archlinux
pacman-key --add /etc/pacman.d/gnupg/arch-lunics.gpg
pacman-key --lsign-key E14ABE24A88E1131
pacman -Sy
```
I don't need to use my own arch repo atm but I'll dig into it later.
We can close this issue if you want, I'm not good with managing gpg keys, I must have been wrong somewhere.

**Comment by Foxboron** [comment]
Thanks for coming back to the issue :)
