### ISSUE TITLE
/etc/resolv.conf is not bind-mounted if the target is a symlink

### ISSUE THREAD

**Issue by nl6720** [archlinux/arch-install-scripts#55]
If the `/etc/resolv.conf` in the chroot directory is a symlink to `../run/systemd/resolve/stub-resolv.conf`, but the host does not use systemd-resolved, after `arch-chroot`ing, the chroot's `/etc/resolv.conf` will be a broken symlink.

This breaks DNS resolution.

See upstream issue for util-linux' `mount`: https://github.com/util-linux/util-linux/issues/2370

**Comment by YHNdnzj** [comment]
This will be fixed by https://github.com/archlinux/arch-install-scripts/pull/40/commits/e3f9cb6498d01082d19c193e29c70f4d897c7848.

**Comment by nl6720** [comment]
Fix waiting in https://github.com/archlinux/arch-install-scripts/pull/57.
